Repository nucleos/NucleosDompdfBundle, pull requests merged in 2021-02, with the labels that each got.

#172 Replace DompdfWrapperInterface::streamHtml with DompdfWrapperInterface::getStreamResponse
  src/Wrapper/DompdfWrapper.php
  src/Wrapper/DompdfWrapperInterface.php
Labels: BC Break

#246 Fix build trigger
  .github/workflows/continuous-integration.yml
Labels: automerge

#249 Remove changelog linker
  vendor-bin/tools/composer.json
  vendor-bin/tools/composer.lock
Labels: automerge

#253 Improve twig documentation
  README.md
Labels: Documentation
